export const fiats = {
  AFN: {
    code: 'AFN',
    name: 'Afghani',
    minorUnit: 2,
    numericCode: 971,
  },
  EUR: {
    code: 'EUR',
    name: 'Euro',
    minorUnit: 2,
    numericCode: 978,
  },
  ALL: {
    code: 'ALL',
    name: 'Lek',
    minorUnit: 2,
    numericCode: 8,
  },
  DZD: {
    code: 'DZD',
    name: 'Algerian Dinar',
    minorUnit: 2,
    numericCode: 12,
  },
  USD: {
    code: 'USD',
    name: 'US Dollar',
    minorUnit: 2,
    numericCode: 840,
  },
  AOA: {
    code: 'AOA',
    name: 'Kwanza',
    minorUnit: 2,
    numericCode: 973,
  },
  XCD: {
    code: 'XCD',
    name: 'East Caribbean Dollar',
    minorUnit: 2,
    numericCode: 951,
  },
  ARS: {
    code: 'ARS',
    name: 'Argentine Peso',
    minorUnit: 2,
    numericCode: 32,
  },
  AMD: {
    code: 'AMD',
    name: 'Armenian Dram',
    minorUnit: 2,
    numericCode: 51,
  },
  AWG: {
    code: 'AWG',
    name: 'Aruban Florin',
    minorUnit: 2,
    numericCode: 533,
  },
  AUD: {
    code: 'AUD',
    name: 'Australian Dollar',
    minorUnit: 2,
    numericCode: 36,
  },
  AZN: {
    code: 'AZN',
    name: 'Azerbaijan Manat',
    minorUnit: 2,
    numericCode: 944,
  },
  BSD: {
    code: 'BSD',
    name: 'Bahamian Dollar',
    minorUnit: 2,
    numericCode: 44,
  },
  BHD: {
    code: 'BHD',
    name: 'Bahraini Dinar',
    minorUnit: 3,
    numericCode: 48,
  },
  BDT: {
    code: 'BDT',
    name: 'Taka',
    minorUnit: 2,
    numericCode: 50,
  },
  BBD: {
    code: 'BBD',
    name: 'Barbados Dollar',
    minorUnit: 2,
    numericCode: 52,
  },
  BYN: {
    code: 'BYN',
    name: 'Belarusian Ruble',
    minorUnit: 2,
    numericCode: 933,
  },
  BZD: {
    code: 'BZD',
    name: 'Belize Dollar',
    minorUnit: 2,
    numericCode: 84,
  },
  XOF: {
    code: 'XOF',
    name: 'CFA Franc BCEAO',
    minorUnit: 0,
    numericCode: 952,
  },
  BMD: {
    code: 'BMD',
    name: 'Bermudian Dollar',
    minorUnit: 2,
    numericCode: 60,
  },
  INR: {
    code: 'INR',
    name: 'Indian Rupee',
    minorUnit: 2,
    numericCode: 356,
  },
  BTN: {
    code: 'BTN',
    name: 'Ngultrum',
    minorUnit: 2,
    numericCode: 64,
  },
  BOB: {
    code: 'BOB',
    name: 'Boliviano',
    minorUnit: 2,
    numericCode: 68,
  },
  BOV: {
    code: 'BOV',
    name: 'Mvdol',
    minorUnit: 2,
    numericCode: 984,
  },
  BAM: {
    code: 'BAM',
    name: 'Convertible Mark',
    minorUnit: 2,
    numericCode: 977,
  },
  BWP: {
    code: 'BWP',
    name: 'Pula',
    minorUnit: 2,
    numericCode: 72,
  },
  NOK: {
    code: 'NOK',
    name: 'Norwegian Krone',
    minorUnit: 2,
    numericCode: 578,
  },
  BRL: {
    code: 'BRL',
    name: 'Brazilian Real',
    minorUnit: 2,
    numericCode: 986,
  },
  BND: {
    code: 'BND',
    name: 'Brunei Dollar',
    minorUnit: 2,
    numericCode: 96,
  },
  BGN: {
    code: 'BGN',
    name: 'Bulgarian Lev',
    minorUnit: 2,
    numericCode: 975,
  },
  BIF: {
    code: 'BIF',
    name: 'Burundi Franc',
    minorUnit: 0,
    numericCode: 108,
  },
  CVE: {
    code: 'CVE',
    name: 'Cabo Verde Escudo',
    minorUnit: 2,
    numericCode: 132,
  },
  KHR: {
    code: 'KHR',
    name: 'Riel',
    minorUnit: 2,
    numericCode: 116,
  },
  XAF: {
    code: 'XAF',
    name: 'CFA Franc BEAC',
    minorUnit: 0,
    numericCode: 950,
  },
  CAD: {
    code: 'CAD',
    name: 'Canadian Dollar',
    minorUnit: 2,
    numericCode: 124,
  },
  KYD: {
    code: 'KYD',
    name: 'Cayman Islands Dollar',
    minorUnit: 2,
    numericCode: 136,
  },
  CLP: {
    code: 'CLP',
    name: 'Chilean Peso',
    minorUnit: 0,
    numericCode: 152,
  },
  CLF: {
    code: 'CLF',
    name: 'Unidad de Fomento',
    minorUnit: 4,
    numericCode: 990,
  },
  CNY: {
    code: 'CNY',
    name: 'Yuan Renminbi',
    minorUnit: 2,
    numericCode: 156,
  },
  COP: {
    code: 'COP',
    name: 'Colombian Peso',
    minorUnit: 2,
    numericCode: 170,
  },
  COU: {
    code: 'COU',
    name: 'Unidad de Valor Real',
    minorUnit: 2,
    numericCode: 970,
  },
  KMF: {
    code: 'KMF',
    name: 'Comorian Franc ',
    minorUnit: 0,
    numericCode: 174,
  },
  CDF: {
    code: 'CDF',
    name: 'Congolese Franc',
    minorUnit: 2,
    numericCode: 976,
  },
  NZD: {
    code: 'NZD',
    name: 'New Zealand Dollar',
    minorUnit: 2,
    numericCode: 554,
  },
  CRC: {
    code: 'CRC',
    name: 'Costa Rican Colon',
    minorUnit: 2,
    numericCode: 188,
  },
  HRK: {
    code: 'HRK',
    name: 'Kuna',
    minorUnit: 2,
    numericCode: 191,
  },
  CUP: {
    code: 'CUP',
    name: 'Cuban Peso',
    minorUnit: 2,
    numericCode: 192,
  },
  CUC: {
    code: 'CUC',
    name: 'Peso Convertible',
    minorUnit: 2,
    numericCode: 931,
  },
  ANG: {
    code: 'ANG',
    name: 'Netherlands Antillean Guilder',
    minorUnit: 2,
    numericCode: 532,
  },
  CZK: {
    code: 'CZK',
    name: 'Czech Koruna',
    minorUnit: 2,
    numericCode: 203,
  },
  DKK: {
    code: 'DKK',
    name: 'Danish Krone',
    minorUnit: 2,
    numericCode: 208,
  },
  DJF: {
    code: 'DJF',
    name: 'Djibouti Franc',
    minorUnit: 0,
    numericCode: 262,
  },
  DOP: {
    code: 'DOP',
    name: 'Dominican Peso',
    minorUnit: 2,
    numericCode: 214,
  },
  EGP: {
    code: 'EGP',
    name: 'Egyptian Pound',
    minorUnit: 2,
    numericCode: 818,
  },
  SVC: {
    code: 'SVC',
    name: 'El Salvador Colon',
    minorUnit: 2,
    numericCode: 222,
  },
  ERN: {
    code: 'ERN',
    name: 'Nakfa',
    minorUnit: 2,
    numericCode: 232,
  },
  ETB: {
    code: 'ETB',
    name: 'Ethiopian Birr',
    minorUnit: 2,
    numericCode: 230,
  },
  FKP: {
    code: 'FKP',
    name: 'Falkland Islands Pound',
    minorUnit: 2,
    numericCode: 238,
  },
  FJD: {
    code: 'FJD',
    name: 'Fiji Dollar',
    minorUnit: 2,
    numericCode: 242,
  },
  XPF: {
    code: 'XPF',
    name: 'CFP Franc',
    minorUnit: 0,
    numericCode: 953,
  },
  GMD: {
    code: 'GMD',
    name: 'Dalasi',
    minorUnit: 2,
    numericCode: 270,
  },
  GEL: {
    code: 'GEL',
    name: 'Lari',
    minorUnit: 2,
    numericCode: 981,
  },
  GHS: {
    code: 'GHS',
    name: 'Ghana Cedi',
    minorUnit: 2,
    numericCode: 936,
  },
  GIP: {
    code: 'GIP',
    name: 'Gibraltar Pound',
    minorUnit: 2,
    numericCode: 292,
  },
  GTQ: {
    code: 'GTQ',
    name: 'Quetzal',
    minorUnit: 2,
    numericCode: 320,
  },
  GBP: {
    code: 'GBP',
    name: 'Pound Sterling',
    minorUnit: 2,
    numericCode: 826,
  },
  GNF: {
    code: 'GNF',
    name: 'Guinean Franc',
    minorUnit: 0,
    numericCode: 324,
  },
  GYD: {
    code: 'GYD',
    name: 'Guyana Dollar',
    minorUnit: 2,
    numericCode: 328,
  },
  HTG: {
    code: 'HTG',
    name: 'Gourde',
    minorUnit: 2,
    numericCode: 332,
  },
  HNL: {
    code: 'HNL',
    name: 'Lempira',
    minorUnit: 2,
    numericCode: 340,
  },
  HKD: {
    code: 'HKD',
    name: 'Hong Kong Dollar',
    minorUnit: 2,
    numericCode: 344,
  },
  HUF: {
    code: 'HUF',
    name: 'Forint',
    minorUnit: 2,
    numericCode: 348,
  },
  ISK: {
    code: 'ISK',
    name: 'Iceland Krona',
    minorUnit: 0,
    numericCode: 352,
  },
  IDR: {
    code: 'IDR',
    name: 'Rupiah',
    minorUnit: 2,
    numericCode: 360,
  },
  XDR: {
    code: 'XDR',
    name: 'SDR (Special Drawing Right)',
    minorUnit: 0,
    numericCode: 960,
  },
  IRR: {
    code: 'IRR',
    name: 'Iranian Rial',
    minorUnit: 2,
    numericCode: 364,
  },
  IQD: {
    code: 'IQD',
    name: 'Iraqi Dinar',
    minorUnit: 3,
    numericCode: 368,
  },
  ILS: {
    code: 'ILS',
    name: 'New Israeli Sheqel',
    minorUnit: 2,
    numericCode: 376,
  },
  JMD: {
    code: 'JMD',
    name: 'Jamaican Dollar',
    minorUnit: 2,
    numericCode: 388,
  },
  JPY: {
    code: 'JPY',
    name: 'Yen',
    minorUnit: 0,
    numericCode: 392,
  },
  JOD: {
    code: 'JOD',
    name: 'Jordanian Dinar',
    minorUnit: 3,
    numericCode: 400,
  },
  KZT: {
    code: 'KZT',
    name: 'Tenge',
    minorUnit: 2,
    numericCode: 398,
  },
  KES: {
    code: 'KES',
    name: 'Kenyan Shilling',
    minorUnit: 2,
    numericCode: 404,
  },
  KPW: {
    code: 'KPW',
    name: 'North Korean Won',
    minorUnit: 2,
    numericCode: 408,
  },
  KRW: {
    code: 'KRW',
    name: 'Won',
    minorUnit: 0,
    numericCode: 410,
  },
  KWD: {
    code: 'KWD',
    name: 'Kuwaiti Dinar',
    minorUnit: 3,
    numericCode: 414,
  },
  KGS: {
    code: 'KGS',
    name: 'Som',
    minorUnit: 2,
    numericCode: 417,
  },
  LAK: {
    code: 'LAK',
    name: 'Lao Kip',
    minorUnit: 2,
    numericCode: 418,
  },
  LBP: {
    code: 'LBP',
    name: 'Lebanese Pound',
    minorUnit: 2,
    numericCode: 422,
  },
  LSL: {
    code: 'LSL',
    name: 'Loti',
    minorUnit: 2,
    numericCode: 426,
  },
  ZAR: {
    code: 'ZAR',
    name: 'Rand',
    minorUnit: 2,
    numericCode: 710,
  },
  LRD: {
    code: 'LRD',
    name: 'Liberian Dollar',
    minorUnit: 2,
    numericCode: 430,
  },
  LYD: {
    code: 'LYD',
    name: 'Libyan Dinar',
    minorUnit: 3,
    numericCode: 434,
  },
  CHF: {
    code: 'CHF',
    name: 'Swiss Franc',
    minorUnit: 2,
    numericCode: 756,
  },
  MOP: {
    code: 'MOP',
    name: 'Pataca',
    minorUnit: 2,
    numericCode: 446,
  },
  MKD: {
    code: 'MKD',
    name: 'Denar',
    minorUnit: 2,
    numericCode: 807,
  },
  MGA: {
    code: 'MGA',
    name: 'Malagasy Ariary',
    minorUnit: 2,
    numericCode: 969,
  },
  MWK: {
    code: 'MWK',
    name: 'Malawi Kwacha',
    minorUnit: 2,
    numericCode: 454,
  },
  MYR: {
    code: 'MYR',
    name: 'Malaysian Ringgit',
    minorUnit: 2,
    numericCode: 458,
  },
  MVR: {
    code: 'MVR',
    name: 'Rufiyaa',
    minorUnit: 2,
    numericCode: 462,
  },
  MRU: {
    code: 'MRU',
    name: 'Ouguiya',
    minorUnit: 2,
    numericCode: 929,
  },
  MUR: {
    code: 'MUR',
    name: 'Mauritius Rupee',
    minorUnit: 2,
    numericCode: 480,
  },
  XUA: {
    code: 'XUA',
    name: 'ADB Unit of Account',
    minorUnit: 0,
    numericCode: 965,
  },
  MXN: {
    code: 'MXN',
    name: 'Mexican Peso',
    minorUnit: 2,
    numericCode: 484,
  },
  MXV: {
    code: 'MXV',
    name: 'Mexican Unidad de Inversion (UDI)',
    minorUnit: 2,
    numericCode: 979,
  },
  MDL: {
    code: 'MDL',
    name: 'Moldovan Leu',
    minorUnit: 2,
    numericCode: 498,
  },
  MNT: {
    code: 'MNT',
    name: 'Tugrik',
    minorUnit: 2,
    numericCode: 496,
  },
  MAD: {
    code: 'MAD',
    name: 'Moroccan Dirham',
    minorUnit: 2,
    numericCode: 504,
  },
  MZN: {
    code: 'MZN',
    name: 'Mozambique Metical',
    minorUnit: 2,
    numericCode: 943,
  },
  MMK: {
    code: 'MMK',
    name: 'Kyat',
    minorUnit: 2,
    numericCode: 104,
  },
  NAD: {
    code: 'NAD',
    name: 'Namibia Dollar',
    minorUnit: 2,
    numericCode: 516,
  },
  NPR: {
    code: 'NPR',
    name: 'Nepalese Rupee',
    minorUnit: 2,
    numericCode: 524,
  },
  NIO: {
    code: 'NIO',
    name: 'Cordoba Oro',
    minorUnit: 2,
    numericCode: 558,
  },
  NGN: {
    code: 'NGN',
    name: 'Naira',
    minorUnit: 2,
    numericCode: 566,
  },
  OMR: {
    code: 'OMR',
    name: 'Rial Omani',
    minorUnit: 3,
    numericCode: 512,
  },
  PKR: {
    code: 'PKR',
    name: 'Pakistan Rupee',
    minorUnit: 2,
    numericCode: 586,
  },
  PAB: {
    code: 'PAB',
    name: 'Balboa',
    minorUnit: 2,
    numericCode: 590,
  },
  PGK: {
    code: 'PGK',
    name: 'Kina',
    minorUnit: 2,
    numericCode: 598,
  },
  PYG: {
    code: 'PYG',
    name: 'Guarani',
    minorUnit: 0,
    numericCode: 600,
  },
  PEN: {
    code: 'PEN',
    name: 'Sol',
    minorUnit: 2,
    numericCode: 604,
  },
  PHP: {
    code: 'PHP',
    name: 'Philippine Piso',
    minorUnit: 2,
    numericCode: 608,
  },
  PLN: {
    code: 'PLN',
    name: 'Zloty',
    minorUnit: 2,
    numericCode: 985,
  },
  QAR: {
    code: 'QAR',
    name: 'Qatari Rial',
    minorUnit: 2,
    numericCode: 634,
  },
  RON: {
    code: 'RON',
    name: 'Romanian Leu',
    minorUnit: 2,
    numericCode: 946,
  },
  RUB: {
    code: 'RUB',
    name: 'Russian Ruble',
    minorUnit: 2,
    numericCode: 643,
  },
  RWF: {
    code: 'RWF',
    name: 'Rwanda Franc',
    minorUnit: 0,
    numericCode: 646,
  },
  SHP: {
    code: 'SHP',
    name: 'Saint Helena Pound',
    minorUnit: 2,
    numericCode: 654,
  },
  WST: {
    code: 'WST',
    name: 'Tala',
    minorUnit: 2,
    numericCode: 882,
  },
  STN: {
    code: 'STN',
    name: 'Dobra',
    minorUnit: 2,
    numericCode: 930,
  },
  SAR: {
    code: 'SAR',
    name: 'Saudi Riyal',
    minorUnit: 2,
    numericCode: 682,
  },
  RSD: {
    code: 'RSD',
    name: 'Serbian Dinar',
    minorUnit: 2,
    numericCode: 941,
  },
  SCR: {
    code: 'SCR',
    name: 'Seychelles Rupee',
    minorUnit: 2,
    numericCode: 690,
  },
  SLL: {
    code: 'SLL',
    name: 'Leone',
    minorUnit: 2,
    numericCode: 694,
  },
  SGD: {
    code: 'SGD',
    name: 'Singapore Dollar',
    minorUnit: 2,
    numericCode: 702,
  },
  XSU: {
    code: 'XSU',
    name: 'Sucre',
    minorUnit: 0,
    numericCode: 994,
  },
  SBD: {
    code: 'SBD',
    name: 'Solomon Islands Dollar',
    minorUnit: 2,
    numericCode: 90,
  },
  SOS: {
    code: 'SOS',
    name: 'Somali Shilling',
    minorUnit: 2,
    numericCode: 706,
  },
  SSP: {
    code: 'SSP',
    name: 'South Sudanese Pound',
    minorUnit: 2,
    numericCode: 728,
  },
  LKR: {
    code: 'LKR',
    name: 'Sri Lanka Rupee',
    minorUnit: 2,
    numericCode: 144,
  },
  SDG: {
    code: 'SDG',
    name: 'Sudanese Pound',
    minorUnit: 2,
    numericCode: 938,
  },
  SRD: {
    code: 'SRD',
    name: 'Surinam Dollar',
    minorUnit: 2,
    numericCode: 968,
  },
  SZL: {
    code: 'SZL',
    name: 'Lilangeni',
    minorUnit: 2,
    numericCode: 748,
  },
  SEK: {
    code: 'SEK',
    name: 'Swedish Krona',
    minorUnit: 2,
    numericCode: 752,
  },
  CHE: {
    code: 'CHE',
    name: 'WIR Euro',
    minorUnit: 2,
    numericCode: 947,
  },
  CHW: {
    code: 'CHW',
    name: 'WIR Franc',
    minorUnit: 2,
    numericCode: 948,
  },
  SYP: {
    code: 'SYP',
    name: 'Syrian Pound',
    minorUnit: 2,
    numericCode: 760,
  },
  TWD: {
    code: 'TWD',
    name: 'New Taiwan Dollar',
    minorUnit: 2,
    numericCode: 901,
  },
  TJS: {
    code: 'TJS',
    name: 'Somoni',
    minorUnit: 2,
    numericCode: 972,
  },
  TZS: {
    code: 'TZS',
    name: 'Tanzanian Shilling',
    minorUnit: 2,
    numericCode: 834,
  },
  THB: {
    code: 'THB',
    name: 'Baht',
    minorUnit: 2,
    numericCode: 764,
  },
  TOP: {
    code: 'TOP',
    name: 'Pa’anga',
    minorUnit: 2,
    numericCode: 776,
  },
  TTD: {
    code: 'TTD',
    name: 'Trinidad and Tobago Dollar',
    minorUnit: 2,
    numericCode: 780,
  },
  TND: {
    code: 'TND',
    name: 'Tunisian Dinar',
    minorUnit: 3,
    numericCode: 788,
  },
  TRY: {
    code: 'TRY',
    name: 'Turkish Lira',
    minorUnit: 2,
    numericCode: 949,
  },
  TMT: {
    code: 'TMT',
    name: 'Turkmenistan New Manat',
    minorUnit: 2,
    numericCode: 934,
  },
  UGX: {
    code: 'UGX',
    name: 'Uganda Shilling',
    minorUnit: 0,
    numericCode: 800,
  },
  UAH: {
    code: 'UAH',
    name: 'Hryvnia',
    minorUnit: 2,
    numericCode: 980,
  },
  AED: {
    code: 'AED',
    name: 'UAE Dirham',
    minorUnit: 2,
    numericCode: 784,
  },
  USN: {
    code: 'USN',
    name: 'US Dollar (Next day)',
    minorUnit: 2,
    numericCode: 997,
  },
  UYU: {
    code: 'UYU',
    name: 'Peso Uruguayo',
    minorUnit: 2,
    numericCode: 858,
  },
  UYI: {
    code: 'UYI',
    name: 'Uruguay Peso en Unidades Indexadas (URUIURUI)',
    minorUnit: 0,
    numericCode: 940,
  },
  UZS: {
    code: 'UZS',
    name: 'Uzbekistan Sum',
    minorUnit: 2,
    numericCode: 860,
  },
  VUV: {
    code: 'VUV',
    name: 'Vatu',
    minorUnit: 0,
    numericCode: 548,
  },
  VEF: {
    code: 'VEF',
    name: 'Bolívar',
    minorUnit: 2,
    numericCode: 937,
  },
  VND: {
    code: 'VND',
    name: 'Dong',
    minorUnit: 0,
    numericCode: 704,
  },
  YER: {
    code: 'YER',
    name: 'Yemeni Rial',
    minorUnit: 2,
    numericCode: 886,
  },
  ZMW: {
    code: 'ZMW',
    name: 'Zambian Kwacha',
    minorUnit: 2,
    numericCode: 967,
  },
  ZWL: {
    code: 'ZWL',
    name: 'Zimbabwe Dollar',
    minorUnit: 2,
    numericCode: 932,
  },
  XBA: {
    code: 'XBA',
    name: 'Bond Markets Unit European Composite Unit (EURCO)',
    minorUnit: 0,
    numericCode: 955,
  },
  XBB: {
    code: 'XBB',
    name: 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
    minorUnit: 0,
    numericCode: 956,
  },
  XBC: {
    code: 'XBC',
    name: 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
    minorUnit: 0,
    numericCode: 957,
  },
  XBD: {
    code: 'XBD',
    name: 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
    minorUnit: 0,
    numericCode: 958,
  },
  XTS: {
    code: 'XTS',
    name: 'Codes specifically reserved for testing purposes',
    minorUnit: 0,
    numericCode: 963,
  },
  XXX: {
    code: 'XXX',
    currency:
      'The codes assigned for transactions where no currency is involved',
    minorUnit: 0,
    numericCode: 999,
  },
  XAU: {
    code: 'XAU',
    name: 'Gold',
    minorUnit: 0,
    numericCode: 959,
  },
  XPD: {
    code: 'XPD',
    name: 'Palladium',
    minorUnit: 0,
    numericCode: 964,
  },
  XPT: {
    code: 'XPT',
    name: 'Platinum',
    minorUnit: 0,
    numericCode: 962,
  },
  XAG: {
    code: 'XAG',
    name: 'Silver',
    minorUnit: 0,
    numericCode: 961,
  },
};
