export enum BookieName {
  Caliente = 'Caliente',
  Playdoit = 'Playdoit',
  BigBola = 'BigBola',
  Pinnacle = 'Pinnacle',
  Bet365 = 'Bet365',
  Stake = 'Stake',
  Betway = 'Betway',
  Betfair = 'Betfair',
  Cloudbet = 'Cloudbet',
  Matchbook = 'Matchbook',
  _1xBet = '1xBet',
  Melbet = 'Melbet',
  Dafabet = 'Dafabet',
  Betcris = 'Betcris',
  Bookmaker = 'Bookmaker',
  BetInAsia = 'BetInAsia',
  Bwin = 'Bwin',
  BetDex = 'BetDex',
  SXBet = 'SXBet',
  SportsbetIO = 'SportsbetIO',
  Thunderpick = 'Thunderpick',
}
